<?php
  $array = [
    "L’Opus Dei", 
    "L’adoctrina-ment de TV3", 
    "La variant Òmicron", 
    "Un penis superheroi que lluita per la justícia",
    "Tsunami Democràtic",
    "El confinament",
    "La Batalla de l'Ebre",
    "Gabriel Rufian",
    "Esquerra",
    "Castellers",
    "El temps",
    "La santa espina",
    "Puta Espanya!",
    "Un pixapins anant a caçar bolets armat",
    "Plats bruts",
    "Pere Aragones",
    "Carles Puigdemont",
    "Miquel iceta",
    "En Shin-Chan fent el monstre del cul",
    "Conills voladors assassins",
    "Camps de concentració",
    "Una unitat antidisturbis fent un examen de mates",
    "Anar de vacances a Susqueda i no tornar",
    "Un borbó a l'atzar", 
    "Un penis de 35 cm", 
    "L’accent de Girona", 
    "Francisco Franco",
    "Les cançons de Bola de Drac en castellà",
    "El burkini",
    "Adolf Hitler",
    "Abascal",
    "Sopa de cabra",
    "Sangtrait",
    "Tallar les vies del AVE a Girona",
    "El jutje Marchena",
    "Els volcans",
    "Amputats",
    "El meu compte bancari",
    "Porno alenany sadomasoquista",
    "Adriannumeritos",
    "El Pulgatejana fent poledance en tanga",
    "Diarrea explosiva",
    "Els rituals de sacrifici de creadors",
    "Ossama Bin Laden",
    "Un grapat de polles en vinagre",
    "Al-Qaida",
    "Gais fotent-se ma",
    "Les prostitutes del camp nou",
    "Un camp de refugiats",
    "El ministre de salut",
    "una dotzena d'esclaus africans",
    "Un pessebre vivent nudista",
    "La teva familia",
    "Els serveis secrets de la Paeria",
    "Un estruç amb monocle prenent un cafè",
    "El teu futur",
    "Un bon bukkake",
    "El president de creadors",
    "Un referèndum il·legal",
    "El papa de roma",
    "Un infectat de covid",
    "Els serveis secrets de la Catalunya nord",
    "Una discoteca d'ambient",
    "Musculman",
    "Grallers",
    "Una palla ben feta",
    "El covid",
    "Atori el ninja",
    "En son Goku",
    "El casquet volador",
    "Els teus genitals",
    "Txernòbil",
    "Eurovisió",
    "les enesimes comisions de creadors",
    "Les 3 bessones",
    "Un gos drogadicte",
    "Els homes",
    "Els CDR",
    "pa amb tomaquet",
    "Les Dones",
    "Futbol femení",
    "Els teus pares",
    "Catalunya Radio",
    "Els argentins",
    "Un Satisfyer",
    "Un nen soldat",
    "Una bona mamada",
    "La moreneta",
    "Semen d'antivacunes",
    "El titafreda jugant a Crusader kings 3"
   
    
];
  $min = 0;
  $max = count($array)-1;

  $rand = rand($min,$max);

  echo $array[$rand]

?>
